---
Name: automated-content-management
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\AutomatedContentManagement\Extensions\SiteConfigExtensionForLLM

SilverStripe\ORM\DataObject:
  extensions:
    - Sunnysideup\AutomatedContentManagement\Extensions\DataObjectExtensionForLLM

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "sunnysideup/automated-content-management:client/dist/automated-content-management.css"
  extra_requirements_javascript:
    - "sunnysideup/automated-content-management:client/dist/automated-content-management.js"
