---
Name: automated-content-management
After: "*"
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\AutomatedContentManagement\Extensions\SiteConfigExtensionForLLM

SilverStripe\ORM\DataObject:
  extensions:
    - Sunnysideup\AutomatedContentManagement\Extensions\DataObjectExtensionForLLM
